# Generated by Django 3.2.5 on 2021-07-08 04:12

import apps.notice.utils
import apps.notice.validators
from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('semester', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eight', 'Eight')], max_length=256)),
                ('image', models.ImageField(upload_to=apps.notice.utils.upload_notice_image_to, validators=[apps.notice.validators.NoticeImageValidator])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
