# Generated by Django 3.2.5 on 2021-07-04 18:30

import apps.notice.utils
import apps.notice.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(upload_to=apps.notice.utils.upload_notice_image_to, validators=[apps.notice.validators.NoticeImageValidator]),
        ),
    ]
