# Generated by Django 3.2.5 on 2021-07-06 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='semester',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eight', 'Eight')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
