# Generated by Django 3.2.5 on 2021-07-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='semester',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eight', 'Eight'), ('all', 'All')], max_length=256),
        ),
    ]
