# Generated by Django 3.2.4 on 2021-06-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210627_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='faculty_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='parents_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
