# Generated by Django 3.2.4 on 2021-06-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210630_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.IntegerField(blank=True, help_text='This is actually the user or student joined to that institute', null=True),
        ),
    ]
